# Use an official Node.js runtime as the base image
FROM node:21

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY frontend/ ./

# Install Next.js app dependencies
RUN npm install

ENV DOCKER_ENV="true"

# Expose port 3000
EXPOSE 3000

RUN npm run build

# Install `serve` to run the application.
RUN npm install -g serve

#CMD [ "npm", "start" ]
CMD ["serve", "-s", "build"]