version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
