# tested with python 3.11.5
# install e.g. with 
# conda env create --prefix ./backend_env -f conda_requirements.yaml
# or
# mamba env create --prefix ./backend_env -f conda_requirements.yaml

channels:
  - defaults
  - conda-forge

dependencies:
  - openssl
  - fastapi
  - uvicorn
  - numpy
  - numba
  - pandas
  - scanpy
  - python-annoy
  - matplotlib
  - pyyaml
  - pip
  - pip:
    - glasbey
    - opentsne
    - numba_progress
